feature: made auth logic
mr-mollusk/ZallService pull request #4
Opened 2023-10-03 08:56 UTC by mr-mollusk

2023-10-03 09:59 UTC, cucunber commented on src/api/api.types.ts
> +export type PaginatedRequest = {
PaginatedQueryParams?

2023-10-03 10:00 UTC, cucunber commented on src/api/instance.api.ts
> +    const access = localStorage.getItem('access');
если я отрублю доступ к кукам, ты пойдешь лесом

2023-10-03 10:27 UTC, cucunber requested changes

2023-10-03 10:27 UTC, cucunber commented on src/api/instance.api.ts
> +        const response = await userApi.refreshToken(refresh);
тебе нужно перед запросом удалить access токен, тк на сервер придет сдохший токен и рефреш тебе вернет 401

2023-10-03 10:27 UTC, cucunber commented on src/api/instance.api.ts
> +    if (error.response?.status === 401) {
мб уберем пирамидку?
if(error.response?.status !== 401){
return error
}
if(!refresh){
return error
}
....

2023-10-03 10:27 UTC, cucunber commented on src/api/user/user.api.ts
> +    return { isError: false, data: data };
сделай общую обертку, которая тебе уже в таком формате будет чет отдавать, в apiInstance опишу, как можно это сделать

2023-10-03 10:27 UTC, cucunber commented on src/models/user.types.ts
> +export interface IUser {
IUserDTO?

2023-10-03 10:27 UTC, cucunber commented on src/store/user/index.ts
> +export const userActions = {...userAsyncActions, ...userSincActions}
userSyncActions?

2023-10-03 10:27 UTC, cucunber commented on src/store/user/user.actions.ts
> +    } else {
зачем тут else?

2023-10-03 10:27 UTC, cucunber commented on src/store/user/user.reducer.ts
> +        console.log();
?

2023-10-03 10:27 UTC, cucunber commented on src/store/user/user.reducer.ts
> +        localStorage.removeItem('refresh');
зачем тут это? При каждой перезагрузке страницы удалять токены? Смысл тогда рефреш и аксес токена?

2023-10-03 10:27 UTC, cucunber commented on src/api/user/user.api.ts
> +const postUser = async (newUser: IUser): PromiseRequestData<Omit<IUser, 'id'>> => {
что за пост юзер? Может лучше createUser/registerUser?

2023-10-03 10:27 UTC, cucunber commented on src/store/user/user.reducer.ts
> +    builder.addCase(userAsyncActions.postUserAction.pending, (state) => {
посмотри в сторону addMatcher

2023-10-03 10:27 UTC, cucunber commented on src/store/user/user.reducer.ts
> +      state.user = initialState.user;
ты можешь только state.isLoading поменять, остальное возьмется из предыдущего стейта

2023-10-15 15:46 UTC, cucunber approved these changes

2023-10-15 15:46 UTC, cucunber commented on src/api/config/api.config.ts
> +    if (access) config.headers.Authorization = `Bearer ${access}`;
if(condition){ ... }

2023-10-15 15:46 UTC, cucunber commented on src/api/config/api.config.ts
> +    const refresh = LocalStorage.getItem<string>('refresh');
название ячеек лучше вынести в константы

2023-10-15 15:46 UTC, cucunber commented on src/store/user/user.actions.ts
> +  'user/postUser',
названия экшенов лучше в константы + в константы названия редъюсеров, чтобы потом можно было их собирать через функции,  а не руками

2023-10-15 15:46 UTC, cucunber commented on src/store/user/user.reducer.ts
> +    builder.addMatcher(isPendingAction, (state) => {
а че для ошибок (почти всех rejected кейсов) нельзя сделать такой же matcher?

2023-10-15 15:46 UTC, cucunber commented on src/utils/apiBuilder.ts
> +export class ApiBuilder {
билдером это тяжело назвать можно назвать

2023-10-16 07:37 UTC, UniverseArc approved these changes

2023-10-16 07:51 UTC, merged